// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    A: typeof import('./../src/components/A.vue')['default']
    B: typeof import('./../src/components/B.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanEmpty: typeof import('vant/es')['Empty']
  }
}

export {}
